[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  FIREBASE_API_KEY = "AIzaSyC9TT03CKV-yj4P8fEUW_J51IaMA29wF0Q"
  FIREBASE_AUTH_DOMAIN = "memify-prod.firebaseapp.com"
  FIREBASE_PROJECT_ID = "memify-prod"
  FIREBASE_STORAGE_BUCKET = "memify-prod.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID = "39176808638"
  FIREBASE_APP_ID = "1:39176808638:web:c22a74e2fdaaadcf3b16ef"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200